##
# travis configuration for oZone base
##

language: cpp
sudo: required
dist: trusty
compiler: gcc

notifications:
  slack: ozonesecurity:G1nKPaoZHfRCvC6GjnvRUB2J
  on_success: never
  on_failure: always

branches:
  only: master

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - make
      - git
      - vim
      - cmake
      - libass-dev
      - libfreetype6-dev
      - libjpeg-dev
      - libjpeg8
      - libtheora-dev
      - libtool
      - libvorbis-dev
      - pkg-config
      - texinfo
      - yasm
      - zlib1g-dev
      - libopenblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - g++-5
      - gcc-5

cache:
    directories:
      - externals/ffmpeg

install: true
      #- cd externals/ffmpeg
      #- ./configure --enable-shared
      #- make -j `grep processor /proc/cpuinfo|wc -l` 
      #- sudo make install 
      #- sudo make install-libs
      #- cd ../dlib
      #- mkdir -p build
      #- cd build
      #- cmake ..
      #- sudo make install 

script:
      - export CXX="g++-5" CC="gcc-5"
      - mkdir -p ~/ozoneroot
      - export $INSTALL_DIR=~/ozoneroot
      - cd $TRAVIS_BUILD_DIR/
      - ./ozone-build.sh
      #- cd $TRAVIS_BUILD_DIR/server
      #- cmake -DOZ_EXAMPLES=ON .
      #- make
      #- sudo make install

